### ISSUE TITLE
Update the website and github for XMPP

### ISSUE THREAD

**Issue by Neustradamus** [horazont/muchopper#1]
https://muclumbus.jabbercat.org/about
"Public Jabber Chat rooms" -> XMPP MUC rooms
"Christopher Muclumbus: A listing of public XMPP/Jabber chat rooms/groups." -> XMPP MUC rooms

"Christopher Muclumbus is a project to provide a list of public chat rooms in the Jabber Instant Messaging network." -> a list of public MUC rooms in the XMPP network.

"To learn more about the technical background of Jabber, visit the home page of the XMPP Standards Foundation. The XMPP Standards Foundation is the organization governing the technical development of XMPP. XMPP is the protocol on which Jabber is built." -> To learn more about the technical background of XMPP, visit the home page of the XMPP Standards Foundation. The XMPP Standards Foundation is the organization governing the technical development of XMPP.

https://github.com/horazont/muchopper
"Public chat room listing of the Jabber/XMPP Instant Messaging network" -> Public MUC room listing of the XMPP network

**Comment by horazont** [comment]
See https://github.com/jabbercat/jabbercat/issues/89 for rationale why we won’t do this.

Thanks for your time.
