### ISSUE TITLE
Support for search on HTTP API

### ISSUE THREAD

**Issue by iNPUTmice** [horazont/muchopper#10]
For privacy reasons I would prefer to implement the HTTP API in my client. However I do like the ability to search without downloading the entire list.

**Comment by horazont** [comment]
I agree that this would be a valuable feature. I am a bit concerned about the server load this may incur, and we’ll have to see how that works out.

@iNPUTmice Do you have a way to roll an update with Conversations having Muclumbus integration to only a part of the users? I’d like to see how it increases the load and how to go from there.

**Comment by horazont** [comment]
@iNPUTmice 
See #11 and [the new documentation](https://search.jabber.network/docs/api#api-1.0-search). Please report any issues over in #11.
