### ISSUE TITLE
Couldn't connect to conference.jugendhacker.de

### ISSUE THREAD

**Issue by jugendhacker** [horazont/muchopper#17]
I already invited muclumbus multiple times into multiple rooms on conference.jugendhacker.de and my ejabberd logs also show me that the s2s works but the rooms on my server never show up in the list... now I'm confused if it's a problem on my side or on the side of muclumbus.

**Comment by horazont** [comment]
@jugendhacker Should be solved now.

The logs reported timeouts attempting to connect to your domain:

```
Sep 08 19:59:25 muclumbus-xmpp /opt/muchopper/muchopper/bot/__main__.py[10553]: DEBUG    muchopper.client.bot.scanner.Scanner conference.jugendhacker.de is a MUC service, forcing scan
Sep 08 19:59:26 muclumbus-xmpp /opt/muchopper/muchopper/bot/__main__.py[10553]: DEBUG    muchopper.client.bot.scanner.Scanner failed to query software version of conference.jugendhacker.de ({urn:ietf:params:xml:ns:xmpp-stanzas}service-unavailable ('No module is handling this query')), ignoring
Sep 08 19:59:27 muclumbus-xmpp /opt/muchopper/muchopper/bot/__main__.py[10553]: DEBUG    muchopper.client.bot.scanner.Scanner got 5 items for MUC domain JID(localpart=None, domain='conference.jugendhacker.de', resource=None)
Sep 08 20:00:25 muclumbus-xmpp /opt/muchopper/muchopper/bot/__main__.py[10553]: WARNING  muchopper.client.bot.scanner.Scanner processing of item ('conference.jugendhacker.de', datetime.datetime(2019, 9, 8, 19, 0, 40, 815319), True) timed out
```

The fact that this happens despite the version query failing (i.e. there is still stream connectivity) is confusing, and I’m not sure how that situation can be caused.

I’m going to dig in the code. For now, your listing seems to be restored. Feel free to comment and/or re-open if you see issues again.

**Comment by horazont** [comment]
Aha! The timeout can happen when the scanner queue runs full.

We’ve seen that situation quite a few times now, need to dig deeper into when the scanner queue can run full without clearing at some point.
