### ISSUE TITLE
Web UI support for XEP-0106: JID Escaping

### ISSUE THREAD

**Issue by ge0rg** [horazont/muchopper#22]
It would be great to support [XEP-0106](https://xmpp.org/extensions/xep-0106.html) in the display, so that unreadable JIDs with `\20` in them become nice and clean...

![image](https://user-images.githubusercontent.com/165635/65159755-de0c1880-da34-11e9-8bc1-b3a2621f6ce8.png)

**Comment by horazont** [comment]
This will work with #28 when we clearly separate name (which may simply be the localpart) and address.
