### ISSUE TITLE
Domain joinxmpp.org

### ISSUE THREAD

**Issue by Maryjane-ai** [horazont/muchopper#24]
Hi all,

Long time fan of XMPP. So much so that a year ago or so together with a friend we got the domain joinxmpp.org, to do a similar project to your webpage.

We never got around to start that project for several reasons. But we kept the domain and we would not mind if someone else actually gave a use to it.

So in short we are willing to transfer that domain for free to your project if your project is interested in it.

PS: made a github account just to contact you guys

**Comment by horazont** [comment]
@Maryjane-ai Thanks for reaching out.

I would prefer to continue this via [Email](mailto:jonas@wielicki.name) or XMPP (xmpp:jonas@wielicki.name) if that’s fine with you. If it is, please send an email or IM to me.

You can also find the same contact information [on the website](https://search.jabbercat.org/contact).

**Comment by Maryjane-ai** [comment]
I'll reach out
