### ISSUE TITLE
Web UI not making good use of desktop full-screen

### ISSUE THREAD

**Issue by ge0rg** [horazont/muchopper#25]
There is much white space on the left, and very very much white space on the right:

![image](https://user-images.githubusercontent.com/165635/65691122-960e7680-e070-11e9-9e7f-5c65f2ef2682.png)

**Comment by horazont** [comment]
Since wide results aren’t really nice to look at (@mwild1 has pointed that out correctly), we’ll go more towards left-aligning all the things more (including the pagination).
