### ISSUE TITLE
Copy to clipboard scrolls to bottom

### ISSUE THREAD

**Issue by Zash** [horazont/muchopper#34]
1. Click icon to copy JID to clipboard.

*Expected:* JID copied to clipboard, no other effects.

*Actual:* Page scrolled to bottom (JID copied tho)

- Browser: Firefox 60.9.0esr

**Comment by horazont** [comment]
Cannot reproduce with Firefox 69.0.1.

**Comment by horazont** [comment]
Neither with Chromium Version 76.0.3809.100. 

@Zash Does this happen immediately after clicking the copy button, or only after the notice is hidden?

**Comment by Zash** [comment]
Immediately on releasing the mouse button.

Browser console says

> `Fallback: Copying text command was successful`

On Debian stable.

**Comment by Zash** [comment]
Works, thanks.
