### ISSUE TITLE
IQ API requires "optional" `q` parameter.

### ISSUE THREAD

**Issue by ge0rg** [horazont/muchopper#4]
When sending a search request via the IQ API, it is not possible to pass an empty `q` value or no `q` field at all, it will be responded to with:

```xml
<iq to="..." id="Bwn0D-553" type="error" from="muchopper">
  <error type="cancel"><undefined-condition xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error>
</iq>
```

Please:
* [ ] fix the error to contain a developer-readable explanation, stack trace or some other useful message
* [ ] make the `q` parameter actually optional, to allow fetching the Top N MUCs by population

**Comment by horazont** [comment]
This was a raw traceback; we won’t give details about raw tracebacks, because a remote developer can’t do anything about them anyways. They are already logged as ERROR, so even with default settings it would appear in any logfile.
