### ISSUE TITLE
MUC List Paging (XEP-0059)

### ISSUE THREAD

**Issue by Zash** [horazont/muchopper#58]
Some MUC hosts (notably the IETF one) have so many channels they require paging by the use of [Result Set Management](https://xmpp.org/extensions/xep-0059.html) in order to retrieve the full list, otherwise the list is incomplete.

**Comment by horazont** [comment]
Noooooooooooooooooooooooooo… I was *so* dreading this one :D

Can’t they all just pull a jabber.org and send all the MUCs in one gigantic disco#items response? :(
