### ISSUE TITLE
Avatars for conference.monocles.de are not displayed

### ISSUE THREAD

**Issue by GreenLunar** [horazont/muchopper#65]
https://search.jabber.network/search?q=+monocles&f=y&sinaddr=on&sindescr=on&sinname=on

Examples:
xmpp:development@conference.monocles.de?join --> https://monocles.wiki/images/monocles_dev.png
xmpp:support@conference.monocles.de?join --> https://monocles.de/more/assets/images/site-logo.svg

**Comment by horazont** [comment]
@GreenLunar  https://search.jabber.network/docs/faq Please see the "Why is my room’s avatar not shown?" section.
