### ISSUE TITLE
Provide single-room JSON API

### ISSUE THREAD

**Issue by ge0rg** [horazont/muchopper#8]
It would be great to be able to pull a single room's info via JSON, e.g. like this:

```sh
# totally not mocked up request
curl https://search.jabber.network/api/1.0/room/xmpp@chat.yax.im \
     -H "Content-Type: application/json"
```

```json
{
      "address": "xmpp@chat.yax.im", 
      "anonymity_mode": "semi", 
      "description": "You might still be in!", 
      "is_open": true, 
      "language": "sjn", 
      "name": "Schr\u00f6dingers Chat", 
      "nusers": 34
}
```
And even more awesome if it could render an SVG (or PNG) badge for the room, similar to these ones:

* https://shields.io/category/chat
* https://chat.prosody.im/badge
* https://chat.tatoeba.org/badge

**Comment by horazont** [comment]
What is your use-case? Would you prefer to have this over XMPP?

Badges sound like a good thing indeed.

**Comment by ge0rg** [comment]
My use case is badges on websites, so no need for an XMPP API. The JSON-API would just be an intermediate step in a self-hosted badge API, but if you can sensibly provide both, it would be even better obviously.
